services:
  - type: web
    name: tradingview-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: LINE_NOTIFY_TOKEN
        sync: false
